# Generated by Django 4.2.5 on 2023-09-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='short_intro',
            new_name='bio',
        ),
    ]
