# Generated by Django 4.2.5 on 2023-09-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_owner_review_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
    ]
