# Generated by Django 4.2.5 on 2023-09-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_options_alter_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created']},
        ),
    ]
